# Feature Engineering Analysis

**Purpose:** Investigate potential new features that could improve model performance, based on insights from descriptive and inferential analysis.

**Tasks:** 

1. Create new features by combining existing ones (e.g., date-based features like "day of the week").
2. Encode categorical variables: Label encoding, One-Hot encoding, or similar techniques.
3. Feature scaling: Min-Max scaling, Standardization.
4. Feature selection techniques (e.g., based on correlation matrix, mutual information, feature importance).

In [ ]:
import json

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scipy import stats
import statsmodels.api as sm
import statsmodels.stats.api as sms

pd.set_option('display.max_columns', None)

In [ ]:
# reading data
df = pd.read_csv(r"D:\Doccuments\GitHub\End-to-End-MLOps-Pipeline\data\raw\fraud test.csv")
df.shape

(555719, 23)

In [ ]:
data = df[df.columns[1:]].copy()
data.head(3)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,21/06/2020 12:14,2.291160e+15,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,19/03/1968,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,21/06/2020 12:14,3.573030e+15,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",17/01/1990,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,21/06/2020 12:14,3.598220e+15,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,NY,11710,40.6729,-73.5365,34496,"Librarian, public",21/10/1970,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0

In [ ]:
cols_div_path = r"D:\Doccuments\GitHub\End-to-End-MLOps-Pipeline\notebooks\metadata\Credit_cols_classified.json"
with open(cols_div_path,'r') as file:
    cols_division = json.load(file)
cols_division

{'target_col': 'is_fraud',
 'uniq_cols': ['cc_num', 'trans_num'],
 'num_cols': ['amt', 'city_pop'],
 'cat_cols': ['merchant',
  'category',
  'first',
  'last',
  'gender',
  'street',
  'city',
  'state',
  'job'],
 'loc_cols': ['long', 'lat', 'merch_lat', 'merch_long', 'zip'],
 'time_cols': ['trans_date_trans_time', 'dob', 'unix_time']}

In [ ]:
data["amt_per_pop"] = data["amt"] / (data["city_pop"] + 1e-6)
data["log_amt_per_pop"] = np.log1p(data["amt"]) - np.log1p(data["city_pop"])

The feature `log_amt_per_pop` helps capture:

- High transaction amount in small population → suspicious
- Same amount in large city → less suspicious

In [ ]:
data.groupby(by = "is_fraud")["log_amt_per_pop"].describe().T

is_fraud              0            1
count     553574.000000  2145.000000
mean          -4.831561    -2.826417
std            2.783637     2.658438
min          -14.184395   -12.233963
25%           -6.640328    -4.592013
50%           -4.432446    -2.374136
75%           -2.776941    -0.800687
max            4.122553     3.559684