# Feature Engineering Analysis

**Purpose:** Investigate potential new features that could improve model performance, based on insights from descriptive and inferential analysis.

**Tasks:** 

1. Create new features by combining existing ones (e.g., date-based features like "day of the week").
2. Encode categorical variables: Label encoding, One-Hot encoding, or similar techniques.
3. Feature scaling: Min-Max scaling, Standardization.
4. Feature selection techniques (e.g., based on correlation matrix, mutual information, feature importance).

In [1]:
import json

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scipy import stats
import statsmodels.api as sm
import statsmodels.stats.api as sms

pd.set_option('display.max_columns', None)

In [2]:
# reading data
df = pd.read_csv(r"D:\Doccuments\GitHub\End-to-End-MLOps-Pipeline\data\raw\fraud test.csv")
df.shape

(555719, 23)

In [3]:
data = df[df.columns[1:]].copy()
data.head(3)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,21/06/2020 12:14,2.291160e+15,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,19/03/1968,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,21/06/2020 12:14,3.573030e+15,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",17/01/1990,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,21/06/2020 12:14,3.598220e+15,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,NY,11710,40.6729,-73.5365,34496,"Librarian, public",21/10/1970,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0

In [4]:
cols_div_path = r"D:\Doccuments\GitHub\End-to-End-MLOps-Pipeline\notebooks\metadata\Credit_cols_classified.json"
with open(cols_div_path,'r') as file:
    cols_division = json.load(file)
cols_division

{'target_col': 'is_fraud',
 'uniq_cols': ['cc_num', 'trans_num'],
 'num_cols': ['amt', 'city_pop'],
 'cat_cols': ['merchant',
  'category',
  'first',
  'last',
  'gender',
  'street',
  'city',
  'state',
  'job'],
 'loc_cols': ['long', 'lat', 'merch_lat', 'merch_long', 'zip'],
 'time_cols': ['trans_date_trans_time', 'dob', 'unix_time']}

In [5]:
data["amt_per_pop"] = data["amt"] / (data["city_pop"] + 1e-6)
data["log_amt_per_pop"] = np.log1p(data["amt"]) - np.log1p(data["city_pop"])

The feature `log_amt_per_pop` helps capture:

- High transaction amount in small population → suspicious
- Same amount in large city → less suspicious

In [6]:
data.groupby(by = "is_fraud")["log_amt_per_pop"].describe().T

is_fraud              0            1
count     553574.000000  2145.000000
mean          -4.831561    -2.826417
std            2.783637     2.658438
min          -14.184395   -12.233963
25%           -6.640328    -4.592013
50%           -4.432446    -2.374136
75%           -2.776941    -0.800687
max            4.122553     3.559684

`first`, `last` and `street` can be dropped as it will not give any kind of usefull information.

In [18]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [8]:
cat_cols_encoding = {
    'merchant': "dummie",
    'category': "dummie",
    'gender': "one_hot",
    'city': "label",
    'state': "label",
    'job': "label"
}

In [40]:
def fit_encode_data(data, col_encod_map, drop_first=True):
    data = data.copy()
    encoder_dict = {}

    for col, encod in col_encod_map.items():
        if col not in data.columns:
            continue

        if encod == "label":
            le = LabelEncoder()
            data[col] = le.fit_transform(data[col])

            encoder_dict[col] = {
                "type": "label",
                "encoder": le
            }

        elif encod == "one_hot":
            ohe = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
            transformed = ohe.fit_transform(data[[col]])

            cols = [f"{col}_{c}" for c in ohe.categories_[0]]
            if drop_first:
                transformed = transformed[:, 1:]
                cols = cols[1:]

            df_ohe = pd.DataFrame(transformed, columns=cols, index=data.index)
            data = pd.concat([data.drop(columns=[col]), df_ohe], axis=1)

            encoder_dict[col] = {
                "type": "one_hot",
                "encoder": ohe,
                "columns": cols,
                "drop_first": drop_first
            }

        elif encod == "dummie":
            dummies = pd.get_dummies(data[col], prefix=col, drop_first=drop_first,dtype = int)
            data = pd.concat([data.drop(columns=[col]), dummies], axis=1)

            encoder_dict[col] = {
                "type": "dummie",
                "columns": dummies.columns
            }

    return data, encoder_dict

In [ ]:
# def fit_encode_data(data,col_encod_map:dict,drop_first=True):
#     encoder_dict = {}
#     for col, encod in col_encod_map.items():
#         if encod == "dummie":
#             dummie_encod = pd.get_dummies
#             dummie_encod(data, columns=[col],drop_first=drop_first)
#             encoder_dict[col] = dummie_encod
#         elif encod == "one_hot":
#             one_hot_encod = OneHotEncoder()
#             one_hot_encod.fit(data[[col]])
#             encoder_dict[col] = one_hot_encod
#         elif encod == "label":
#             label_encod = LabelEncoder()
#             label_encod.fit(data[[col]])
#             encoder_dict[col] = label_encod
#         else:
#             print("Encoder Not Implemented please try from the folowing:\n['dummie','one_hot','label']")
#     return encoder_dict

In [41]:
data,encod_dict = fit_encode_data(data,cat_cols_encoding)

In [42]:
data.head()

,trans_date_trans_time,cc_num,amt,first,last,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,amt_per_pop,log_amt_per_pop,merchant_fraud_Abbott-Steuber,merchant_fraud_Abernathy and Sons,merchant_fraud_Abshire PLC,"merchant_fraud_Adams, Kovacek and Kuhlman",merchant_fraud_Adams-Barrows,"merchant_fraud_Altenwerth, Cartwright and Koss",merchant_fraud_Altenwerth-Kilback,merchant_fraud_Ankunding LLC,merchant_fraud_Ankunding-Carroll,"merchant_fraud_Armstrong, Walter and Gottlieb",merchant_fraud_Auer LLC,merchant_fraud_Auer-Mosciski,merchant_fraud_Auer-West,merchant_fraud_Bahringer Group,"merchant_fraud_Bahringer, Bergnaum and Quitzon","merchant_fraud_Bahringer, Osinski and Block","merchant_fraud_Bahringer, Schoen and Corkery",merchant_fraud_Bahringer-Larson,merchant_fraud_Bahringer-Streich,merchant_fraud_Bailey-Morar,merchant_fraud_Balistreri-Nader,merchant_fraud_Barrows PLC,merchant_fraud_Bartoletti and Sons,merchant_fraud_Bartoletti-Wunsch,merchant_fraud_Barton Inc,merchant_fraud_Barton LLC,merchant_fraud_Bashirian Group,merchant_fraud_Bauch-Blanda,merchant_fraud_Bauch-Raynor,merchant_fraud_Baumbach Ltd,"merchant_fraud_Baumbach, Feeney and Morar","merchant_fraud_Baumbach, Hodkiewicz and Walsh","merchant_fraud_Baumbach, Strosin and Nicolas",merchant_fraud_Bechtelar-Rippin,"merchant_fraud_Becker, Harris and Harvey",merchant_fraud_Bednar Group,merchant_fraud_Bednar Inc,merchant_fraud_Bednar PLC,merchant_fraud_Beer-Jast,merchant_fraud_Beier LLC,merchant_fraud_Beier and Sons,merchant_fraud_Beier-Hyatt,merchant_fraud_Berge LLC,"merchant_fraud_Berge, Kautzer and Harris",merchant_fraud_Berge-Hills,merchant_fraud_Berge-Ullrich,merchant_fraud_Bernhard Inc,"merchant_fraud_Bernhard, Grant and Langworth",merchant_fraud_Bernhard-Lesch,merchant_fraud_Bernier and Sons,"merchant_fraud_Bernier, Streich and Jewess","merchant_fraud_Bernier, Volkman and Hoeger","merchant_fraud_Bins, Balistreri and Beatty",merchant_fraud_Bins-Howell,merchant_fraud_Bins-Rice,merchant_fraud_Bins-Tillman,merchant_fraud_Block Group,merchant_fraud_Block-Hauck,merchant_fraud_Block-Parisian,merchant_fraud_Bode-Rempel,merchant_fraud_Bode-Schuster,"merchant_fraud_Boehm, Block and Jakubowski","merchant_fraud_Boehm, Predovic and Reinger",merchant_fraud_Bogisich Inc,merchant_fraud_Bogisich-Homenick,merchant_fraud_Bogisich-Weimann,merchant_fraud_Botsford Ltd,merchant_fraud_Botsford PLC,merchant_fraud_Botsford and Sons,merchant_fraud_Boyer PLC,merchant_fraud_Boyer-Haley,merchant_fraud_Boyer-Reichert,merchant_fraud_Bradtke PLC,"merchant_fraud_Bradtke, Torp and Bahringer",merchant_fraud_Breitenberg LLC,merchant_fraud_Breitenberg-Hermiston,merchant_fraud_Brekke and Sons,merchant_fraud_Brown Inc,merchant_fraud_Brown PLC,"merchant_fraud_Brown, Homenick and Lesch",merchant_fraud_Brown-Greenholt,merchant_fraud_Bruen-Yost,merchant_fraud_Buckridge PLC,merchant_fraud_Carroll PLC,merchant_fraud_Cartwright PLC,merchant_fraud_Cartwright-Harris,"merchant_fraud_Casper, Hand and Zulauf",merchant_fraud_Cassin-Harvey,merchant_fraud_Champlin and Sons,"merchant_fraud_Champlin, Rolfson and Connelly",merchant_fraud_Champlin-Casper,"merchant_fraud_Christiansen, Goyette and Schamberger",merchant_fraud_Christiansen-Gusikowski,merchant_fraud_Cole PLC,"merchant_fraud_Cole, Hills and Jewess",merchant_fraud_Collier Inc,merchant_fraud_Collier LLC,merchant_fraud_Connelly PLC,"merchant_fraud_Connelly, Reichert and Fritsch",merchant_fraud_Connelly-Carter,merchant_fraud_Conroy Ltd,"merchant_fraud_Conroy, Balistreri and Gorczany",merchant_fraud_Conroy-Cruickshank,merchant_fraud_Conroy-Emard,merchant_fraud_Cormier LLC,"merchant_fraud_Cormier, Stracke and Thiel",merchant_fraud_Corwin-Collins,merchant_fraud_Corwin-Gorczany,merchant_fraud_Corwin-Romaguera,"merchant_fraud_Cremin, Hamill and Reichel","merchant_fraud_Crist, Jakubowski and Littel",merchant_fraud_Crona and Sons,"merchant_fraud_Cronin, Kshlerin and Weber",merchant_fraud_Crooks and Sons,merchant_fraud_Cruickshank-Mills,merchant_fraud_Cummerata-Hilpert,merchant_fraud_Cummerata-Jones,merchant_fraud_Cummings Group,merchant_fraud_Cummings LLC,merchant_fraud_Dach-Borer,merchant_fraud_Dach-Nader,"merchant_fraud_Dare, Casper and Bartoletti","merchant_fraud_Dare, Fritsch and Zboncak",merchant_fraud_Dare-Gibson,merchant_fraud_Dare-Marvin,merchant_fraud_Daugherty LLC,"merchant_fraud_Daugherty, Pouros and Beahan",merchant_fraud_Daugherty-Thompson,merchant_fraud_Deckow-Dare,merchant_fraud_Deckow-O'Conner,merchant_fraud_Denesik and Sons,"merchant_fraud_Denesik, Powlowski and Pouros",merchant_fraud_Dibbert and Sons,merchant_fraud_Dibbert-Green,merchant_fraud_Dicki Ltd,merchant_fraud_Dickinson Ltd,merchant_fraud_Dickinson-Rempel,merchant_fraud_Dietrich-Fadel,merchant_fraud_Donnelly LLC,merchant_fraud_Donnelly PLC,merchant_fraud_Dooley Inc,merchant_fraud_Dooley-Thompson,"merchant_fraud_Douglas, DuBuque and McKenzie","merchant_fraud_Douglas, Schneider and Turner",merchant_fraud_Douglas-White,merchant_fraud_Doyle Ltd,merchant_fraud_DuBuque LLC,"merchant_fraud_Durgan, Gislason and Spencer",merchant_fraud_Durgan-Auer,merchant_fraud_Ebert-Daugherty,merchant_fraud_Effertz LLC,"merchant_fraud_Effertz, Welch and Schowalter","merchant_fraud_Eichmann, Bogan and Rodriguez","merchant_fraud_Eichmann, Hayes and Treutel",merchant_fraud_Eichmann-Kilback,merchant_fraud_Eichmann-Russel,merchant_fraud_Emard Inc,merchant_fraud_Emmerich-Luettgen,merchant_fraud_Emmerich-Rau,merchant_fraud_Erdman-Durgan,merchant_fraud_Erdman-Ebert,merchant_fraud_Erdman-Kertzmann,merchant_fraud_Erdman-Schaden,merchant_fraud_Ernser-Feest,merchant_fraud_Ernser-Lynch,merchant_fraud_Fadel Inc,"merchant_fraud_Fadel, Mertz and Rippin",merchant_fraud_Fadel-Hilpert,merchant_fraud_Fahey Inc,"merchant_fraud_Feil, Hilpert and Koss",merchant_fraud_Feil-Morar,"merchant_fraud_Ferry, Lynch and Kautzer","merchant_fraud_Ferry, Reichel and DuBuque",merchant_fraud_Fisher Inc,merchant_fraud_Fisher-Schowalter,merchant_fraud_Flatley Group,merchant_fraud_Flatley-Durgan,merchant_fraud_Frami Group,merchant_fraud_Friesen Inc,merchant_fraud_Friesen Ltd,merchant_fraud_Friesen-D'Amore,merchant_fraud_Friesen-Ortiz,merchant_fraud_Friesen-Stamm,merchant_fraud_Fritsch LLC,merchant_fraud_Fritsch and Sons,merchant_fraud_Funk Group,merchant_fraud_Gaylord-Powlowski,merchant_fraud_Gerhold LLC,merchant_fraud_Gerlach Inc,merchant_fraud_Gibson-Deckow,merchant_fraud_Gislason Group,merchant_fraud_Gleason and Sons,merchant_fraud_Gleason-Macejkovic,"merchant_fraud_Goldner, Kovacek and Abbott",merchant_fraud_Goldner-Lemke,merchant_fraud_Goodwin-Nitzsche,merchant_fraud_Gottlieb Group,"merchant_fraud_Gottlieb, Considine and Schultz",merchant_fraud_Gottlieb-Hansen,merchant_fraud_Goyette Inc,"merchant_fraud_Goyette, Howell and Collier",merchant_fraud_Goyette-Gerhold,merchant_fraud_Goyette-Herzog,merchant_fraud_Graham and Sons,"merchant_fraud_Graham, Hegmann and Hammes","merchant_fraud_Greenfelder, Bartoletti and Davis",merchant_fraud_Greenholt Ltd,"merchant_fraud_Greenholt, Jacobi and Gleason","merchant_fraud_Greenholt, O'Hara and Balistreri",merchant_fraud_Grimes LLC,merchant_fraud_Gulgowski LLC,merchant_fraud_Gutmann Ltd,"merchant_fraud_Gutmann, McLaughlin and Wiza",merchant_fraud_Gutmann-Upton,merchant_fraud_Haag-Blanda,merchant_fraud_Hackett Group,merchant_fraud_Hackett-Lueilwitz,"merchant_fraud_Hagenes, Hermann and Stroman","merchant_fraud_Hagenes, Kohler and Hoppe","merchant_fraud_Hahn, Bahringer and McLaughlin","merchant_fraud_Hahn, Douglas and Schowalter",merchant_fraud_Haley Group,"merchant_fraud_Haley, Batz and Auer","merchant_fraud_Haley, Jewess and Bechtelar",merchant_fraud_Halvorson Group,merchant_fraud_Hamill-D'Amore,merchant_fraud_Hamill-Daugherty,merchant_fraud_Hammes-Beatty,merchant_fraud_Harber Inc,merchant_fraud_Harris Group,merchant_fraud_Harris Inc,"merchant_fraud_Harris, Gusikowski and Heaney","merchant_fraud_Hartmann, Rowe and Hermann","merchant_fraud_Hauck, Dietrich and Funk","merchant_fraud_Hayes, Marquardt and Dibbert",merchant_fraud_Heaney-Marquardt,merchant_fraud_Heathcote LLC,"merchant_fraud_Heathcote, Yost and Kertzmann",merchant_fraud_Heidenreich PLC,merchant_fraud_Heller PLC,"merchant_fraud_Heller, Gutmann and Zieme",merchant_fraud_Heller-Abshire,merchant_fraud_Heller-Langosh,merchant_fraud_Herman Inc,"merchant_fraud_Herman, Treutel and Dickens",merchant_fraud_Hermann and Sons,merchant_fraud_Hermann-Gaylord,"merchant_fraud_Hermiston, Pacocha and Smith","merchant_fraud_Hermiston, Russel and Price",merchant_fraud_Herzog Ltd,"merchant_fraud_Hettinger, McCullough and Fay",merchant_fraud_Hickle Group,"merchant_fraud_Hills, Hegmann and Schaefer",merchant_fraud_Hills-Boyer,merchant_fraud_Hills-Olson,merchant_fraud_Hills-Witting,merchant_fraud_Hilpert-Conroy,"merchant_fraud_Hintz, Bauch and Smith",merchant_fraud_Hintz-Bruen,merchant_fraud_Hirthe-Beier,"merchant_fraud_Hodkiewicz, Prohaska and Paucek",merchant_fraud_Homenick LLC,"merchant_fraud_Hoppe, Harris and Bednar",merchant_fraud_Hoppe-Parisian,merchant_fraud_Howe Ltd,merchant_fraud_Howe PLC,merchant_fraud_Hudson-Grady,merchant_fraud_Hudson-Ratke,merchant_fraud_Huel Ltd,"merchant_fraud_Huel, Hammes and Witting",merchant_fraud_Huel-Langworth,merchant_fraud_Huels-Hahn,merchant_fraud_Huels-Nolan,"merchant_fraud_Hyatt, Russel and Gleichner",merchant_fraud_Hyatt-Blick,merchant_fraud_Jacobi Inc,merchant_fraud_Jacobi and Sons,merchant_fraud_Jakubowski Group,merchant_fraud_Jakubowski Inc,merchant_fraud_Jaskolski-Dibbert,merchant_fraud_Jaskolski-Vandervort,merchant_fraud_Jast Ltd,merchant_fraud_Jast and Sons,merchant_fraud_Jast-McDermott,"merchant_fraud_Jenkins, Hauck and Friesen",merchant_fraud_Jerde-Hermann,merchant_fraud_Jewess LLC,merchant_fraud_Johns Inc,merchant_fraud_Johns-Hoeger,"merchant_fraud_Johnson, Runolfsdottir and Mayer","merchant_fraud_Johnston, Nikolaus and Maggio",merchant_fraud_Johnston-Casper,"merchant_fraud_Jones, Sawayn and Romaguera",merchant_fraud_Kassulke Inc,merchant_fraud_Kassulke PLC,merchant_fraud_Kautzer and Sons,merchant_fraud_Keeling-Crist,merchant_fraud_Kemmer-Buckridge,merchant_fraud_Kemmer-Reinger,merchant_fraud_Kerluke Inc,merchant_fraud_Kerluke PLC,"merchant_fraud_Kerluke, Considine and Macejkovic","merchant_fraud_Kerluke, Kertzmann and Wiza",merchant_fraud_Kerluke-Abshire,merchant_fraud_Kertzmann LLC,merchant_fraud_Kessler Group,merchant_fraud_Kessler Inc,merchant_fraud_Kiehn Inc,merchant_fraud_Kiehn-Emmerich,merchant_fraud_Kihn Inc,"merchant_fraud_Kihn, Abernathy and Douglas","merchant_fraud_Kihn, Brakus and Goyette",merchant_fraud_Kihn-Fritsch,merchant_fraud_Kihn-Schuster,merchant_fraud_Kilback Group,merchant_fraud_Kilback LLC,merchant_fraud_Kilback and Sons,"merchant_fraud_Kilback, Nitzsche and Leffler",merchant_fraud_Kirlin and Sons,merchant_fraud_Klein Group,merchant_fraud_Kling Inc,"merchant_fraud_Kling, Howe and Schneider",merchant_fraud_Kling-Ernser,merchant_fraud_Kling-Grant,merchant_fraud_Klocko LLC,"merchant_fraud_Klocko, Runolfsdottir and Breitenberg",merchant_fraud_Koelpin and Sons,merchant_fraud_Koepp-Parker,merchant_fraud_Koepp-Witting,"merchant_fraud_Kohler, Lindgren and Koelpin","merchant_fraud_Konopelski, Schneider and Hartmann",merchant_fraud_Koss and Sons,"merchant_fraud_Koss, Hansen and Lueilwitz","merchant_fraud_Koss, McLaughlin and Mayer",merchant_fraud_Kovacek Ltd,"merchant_fraud_Kovacek, Dibbert and Ondricka",merchant_fraud_Kozey-Boehm,merchant_fraud_Kozey-Kuhlman,merchant_fraud_Kozey-McDermott,merchant_fraud_Kris-Kertzmann,merchant_fraud_Kris-Padberg,merchant_fraud_Kris-Weimann,merchant_fraud_Kub PLC,merchant_fraud_Kub-Heaney,merchant_fraud_Kuhic Inc,merchant_fraud_Kuhic LLC,"merchant_fraud_Kuhic, Bins and Pfeffer",merchant_fraud_Kuhn Group,merchant_fraud_Kuhn LLC,merchant_fraud_Kulas Group,merchant_fraud_Kunde-Sanford,merchant_fraud_Kunze Inc,"merchant_fraud_Kunze, Larkin and Mayert",merchant_fraud_Kuphal-Bartoletti,merchant_fraud_Kuphal-Predovic,merchant_fraud_Kuphal-Toy,merchant_fraud_Kutch Group,merchant_fraud_Kutch LLC,merchant_fraud_Kutch and Sons,"merchant_fraud_Kutch, Hermiston and Farrell","merchant_fraud_Kutch, Steuber and Gerhold",merchant_fraud_Kutch-Ferry,merchant_fraud_Kutch-Hegmann,merchant_fraud_Kutch-Wilderman,merchant_fraud_Kuvalis Ltd,merchant_fraud_Labadie LLC,"merchant_fraud_Labadie, Treutel and Bode","merchant_fraud_Lakin, Ferry and Beatty","merchant_fraud_Lang, Towne and Schuppe","merchant_fraud_Langosh, Wintheiser and Hyatt",merchant_fraud_Langworth LLC,"merchant_fraud_Langworth, Boehm and Gulgowski",merchant_fraud_Larkin Ltd,"merchant_fraud_Larkin, Stracke and Greenfelder","merchant_fraud_Larson, Quitzon and Spencer",merchant_fraud_Larson-Moen,merchant_fraud_Leannon-Nikolaus,merchant_fraud_Leannon-Ward,merchant_fraud_Lebsack and Sons,"merchant_fraud_Ledner, Hartmann and Feest",merchant_fraud_Ledner-Pfannerstill,merchant_fraud_Leffler-Goldner,"merchant_fraud_Lehner, Mosciski and King","merchant_fraud_Lehner, Reichert and Mills",merchant_fraud_Lemke and Sons,merchant_fraud_Lemke-Gutmann,merchant_fraud_Lesch Ltd,"merchant_fraud_Lesch, D'Amore and Brown","merchant_fraud_Lind, Huel and McClure",merchant_fraud_Lind-Buckridge,merchant_fraud_Little Ltd,"merchant_fraud_Little, Gutmann and Lynch",merchant_fraud_Little-Gleichner,merchant_fraud_Lockman Ltd,"merchant_fraud_Lockman, West and Runte","merchant_fraud_Lowe, Dietrich and Erdman","merchant_fraud_Lubowitz, Terry and Stracke",merchant_fraud_Lubowitz-Walter,merchant_fraud_Luettgen PLC,merchant_fraud_Lynch Ltd,merchant_fraud_Lynch-Mohr,merchant_fraud_Lynch-Wisozk,merchant_fraud_Macejkovic-Lesch,merchant_fraud_Maggio-Fahey,merchant_fraud_Mante Group,"merchant_fraud_Mante, Luettgen and Hackett",merchant_fraud_Marks Inc,merchant_fraud_Marvin-Lind,merchant_fraud_Mayert Group,merchant_fraud_McCullough Group,merchant_fraud_McCullough LLC,"merchant_fraud_McCullough, Hudson and Schuster","merchant_fraud_McDermott, Osinski and Morar",merchant_fraud_McDermott-Rice,merchant_fraud_McDermott-Weimann,merchant_fraud_McGlynn-Heathcote,merchant_fraud_McGlynn-Jaskolski,merchant_fraud_McKenzie-Huels,"merchant_fraud_McLaughlin, Armstrong and Koepp",merchant_fraud_Medhurst Inc,merchant_fraud_Medhurst PLC,"merchant_fraud_Medhurst, Cartwright and Ebert","merchant_fraud_Medhurst, Labadie and Gottlieb","merchant_fraud_Metz, Russel and Metz",merchant_fraud_Metz-Boehm,merchant_fraud_Miller-Harris,merchant_fraud_Miller-Hauck,"merchant_fraud_Moen, Reinger and Murphy",merchant_fraud_Mohr Inc,merchant_fraud_Mohr-Bayer,"merchant_fraud_Monahan, Bogisich and Ledner","merchant_fraud_Monahan, Hermann and Johns",merchant_fraud_Monahan-Morar,"merchant_fraud_Moore, Dibbert and Koepp","merchant_fraud_Moore, Williamson and Emmerich",merchant_fraud_Morar Inc,merchant_fraud_Morissette LLC,merchant_fraud_Morissette PLC,"merchant_fraud_Morissette, Weber and Wiegand",merchant_fraud_Morissette-Schaefer,merchant_fraud_Mosciski Group,"merchant_fraud_Mosciski, Gislason and Mertz","merchant_fraud_Mosciski, Ziemann and Farrell",merchant_fraud_Mraz-Herzog,"merchant_fraud_Mueller, Gerhold and Mueller",merchant_fraud_Murray Ltd,merchant_fraud_Murray-Smitham,merchant_fraud_Nader-Heller,merchant_fraud_Nader-Maggio,"merchant_fraud_Nicolas, Hills and McGlynn",merchant_fraud_Nienow PLC,"merchant_fraud_Nienow, Ankunding and Collier","merchant_fraud_Nienow, Barrows and Romaguera","merchant_fraud_Nitzsche, Kessler and Wolff",merchant_fraud_Nolan-Williamson,"merchant_fraud_O'Connell, Botsford and Hand",merchant_fraud_O'Connell-Ullrich,merchant_fraud_O'Hara-Wilderman,merchant_fraud_O'Keefe-Hudson,merchant_fraud_O'Keefe-Wisoky,"merchant_fraud_O'Reilly, Mohr and Purdy","merchant_fraud_Okuneva, Schneider and Rau","merchant_fraud_Olson, Becker and Koch",merchant_fraud_Ortiz Group,merchant_fraud_Osinski Inc,"merchant_fraud_Osinski, Ledner and Leuschke",merchant_fraud_Pacocha-Bauch,merchant_fraud_Pacocha-O'Reilly,merchant_fraud_Pacocha-Weissnat,merchant_fraud_Padberg-Rogahn,merchant_fraud_Padberg-Sauer,merchant_fraud_Padberg-Welch,merchant_fraud_Pagac LLC,merchant_fraud_Parisian and Sons,"merchant_fraud_Parisian, Schiller and Altenwerth","merchant_fraud_Parker, Nolan and Trantow",merchant_fraud_Parker-Kunde,merchant_fraud_Paucek-Wiza,merchant_fraud_Pfeffer LLC,merchant_fraud_Pfeffer and Sons,merchant_fraud_Pollich LLC,"merchant_fraud_Pouros, Walker and Spencer",merchant_fraud_Pouros-Conroy,merchant_fraud_Pouros-Haag,merchant_fraud_Powlowski-Weimann,merchant_fraud_Predovic Inc,merchant_fraud_Price Inc,merchant_fraud_Prohaska-Murray,merchant_fraud_Prosacco LLC,"merchant_fraud_Prosacco, Kreiger and Kovacek","merchant_fraud_Quitzon, Green and Bashirian",merchant_fraud_Quitzon-Goyette,merchant_fraud_Ratke and Sons,merchant_fraud_Rau and Sons,merchant_fraud_Rau-Grant,merchant_fraud_Rau-Robel,"merchant_fraud_Raynor, Feest and Miller","merchant_fraud_Raynor, Reinger and Hagenes",merchant_fraud_Reichel Inc,merchant_fraud_Reichel LLC,"merchant_fraud_Reichel, Bradtke and Blanda","merchant_fraud_Reichert, Huels and Hoppe","merchant_fraud_Reichert, Rowe and Mraz","merchant_fraud_Reichert, Shanahan and Hayes",merchant_fraud_Reichert-Weissnat,merchant_fraud_Reilly LLC,merchant_fraud_Reilly and Sons,"merchant_fraud_Reilly, Heaney and Cole","merchant_fraud_Reinger, Weissnat and Strosin",merchant_fraud_Rempel Inc,merchant_fraud_Rempel PLC,merchant_fraud_Renner Ltd,merchant_fraud_Reynolds-Schinner,"merchant_fraud_Rippin, Kub and Mann",merchant_fraud_Rippin-VonRueden,"merchant_fraud_Ritchie, Bradtke and Stiedemann","merchant_fraud_Ritchie, Oberbrunner and Cremin","merchant_fraud_Robel, Cummerata and Prosacco","merchant_fraud_Roberts, Daniel and Macejkovic","merchant_fraud_Roberts, Ryan and Smith",merchant_fraud_Roberts-Beahan,merchant_fraud_Rodriguez Group,"merchant_fraud_Rodriguez, Yost and Jenkins","merchant_fraud_Rohan, White and Aufderhar",merchant_fraud_Rolfson-Kunde,merchant_fraud_Romaguera Ltd,merchant_fraud_Romaguera and Sons,"merchant_fraud_Romaguera, Cruickshank and Greenholt","merchant_fraud_Romaguera, Wehner and Tromp",merchant_fraud_Roob LLC,"merchant_fraud_Roob, Conn and Tremblay",merchant_fraud_Roob-Okuneva,"merchant_fraud_Rowe, Batz and Goodwin",merchant_fraud_Rowe-Vandervort,merchant_fraud_Ruecker Group,"merchant_fraud_Ruecker, Beer and Collier",merchant_fraud_Ruecker-Mayert,"merchant_fraud_Runolfsdottir, Mueller and Hand",merchant_fraud_Runolfsson and Sons,"merchant_fraud_Runte, Green and Emard",merchant_fraud_Runte-Mohr,"merchant_fraud_Rutherford, Homenick and Bergstrom",merchant_fraud_Rutherford-Mertz,merchant_fraud_Satterfield-Lowe,merchant_fraud_Sawayn PLC,merchant_fraud_Schaefer Ltd,"merchant_fraud_Schaefer, Fay and Hilll","merchant_fraud_Schaefer, Maggio and Daugherty","merchant_fraud_Schaefer, McGlynn and Bosco",merchant_fraud_Schamberger-O'Keefe,merchant_fraud_Schiller Ltd,"merchant_fraud_Schiller, Blanda and Johnson",merchant_fraud_Schimmel-Olson,merchant_fraud_Schmeler Inc,"merchant_fraud_Schmeler, Bashirian and Price",merchant_fraud_Schmeler-Howe,merchant_fraud_Schmidt and Sons,merchant_fraud_Schmidt-Larkin,merchant_fraud_Schmitt Inc,merchant_fraud_Schmitt Ltd,"merchant_fraud_Schneider, Hayes and Nikolaus",merchant_fraud_Schoen Ltd,"merchant_fraud_Schoen, Kuphal and Nitzsche","merchant_fraud_Schoen, Nienow and Bauch",merchant_fraud_Schoen-Quigley,merchant_fraud_Schroeder Group,"merchant_fraud_Schroeder, Hauck and Treutel","merchant_fraud_Schroeder, Wolff and Hermiston",merchant_fraud_Schulist Ltd,"merchant_fraud_Schultz, Simonis and Little",merchant_fraud_Schumm PLC,"merchant_fraud_Schumm, Bauch and Ondricka","merchant_fraud_Schumm, McLaughlin and Carter",merchant_fraud_Schuppe LLC,"merchant_fraud_Schuppe, Nolan and Hoeger",merchant_fraud_Schuppe-Schuppe,merchant_fraud_Shanahan-Lehner,merchant_fraud_Shields Inc,merchant_fraud_Shields-Wunsch,merchant_fraud_Simonis-Prohaska,merchant_fraud_Skiles LLC,merchant_fraud_Skiles-Ankunding,merchant_fraud_Smith-Stokes,merchant_fraud_Smitham-Boehm,merchant_fraud_Smitham-Schiller,merchant_fraud_Spencer PLC,merchant_fraud_Spencer-R

In [44]:
encod_dict

{'city': {'type': 'label', 'encoder': LabelEncoder()},
 'state': {'type': 'label', 'encoder': LabelEncoder()},
 'job': {'type': 'label', 'encoder': LabelEncoder()}}

In [43]:
def encode_data(data, encoder_dict):
    data = data.copy()

    for col, info in encoder_dict.items():
        if info["type"] == "label":
            le = info["encoder"]
            data[col] = le.transform(data[col])

        elif info["type"] == "one_hot":
            ohe = info["encoder"]
            transformed = ohe.transform(data[[col]])

            cols = [f"{col}_{c}" for c in ohe.categories_[0]]

            if info["drop_first"]:
                transformed = transformed[:, 1:]
                cols = cols[1:]

            df_ohe = pd.DataFrame(transformed, columns=cols, index=data.index)
            data = pd.concat([data.drop(columns=[col]), df_ohe], axis=1)

        elif info["type"] == "dummie":
            dummies = pd.get_dummies(data[col], prefix=col)

            # Align with training columns
            for c in info["columns"]:
                if c not in dummies:
                    dummies[c] = 0

            dummies = dummies[info["columns"]]

            data = pd.concat([data.drop(columns=[col]), dummies], axis=1)

    return data

In [45]:
encode_data(data,encod_dict)

,trans_date_trans_time,cc_num,amt,first,last,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,amt_per_pop,log_amt_per_pop,merchant_fraud_Abbott-Steuber,merchant_fraud_Abernathy and Sons,merchant_fraud_Abshire PLC,"merchant_fraud_Adams, Kovacek and Kuhlman",merchant_fraud_Adams-Barrows,"merchant_fraud_Altenwerth, Cartwright and Koss",merchant_fraud_Altenwerth-Kilback,merchant_fraud_Ankunding LLC,merchant_fraud_Ankunding-Carroll,"merchant_fraud_Armstrong, Walter and Gottlieb",merchant_fraud_Auer LLC,merchant_fraud_Auer-Mosciski,merchant_fraud_Auer-West,merchant_fraud_Bahringer Group,"merchant_fraud_Bahringer, Bergnaum and Quitzon","merchant_fraud_Bahringer, Osinski and Block","merchant_fraud_Bahringer, Schoen and Corkery",merchant_fraud_Bahringer-Larson,merchant_fraud_Bahringer-Streich,merchant_fraud_Bailey-Morar,merchant_fraud_Balistreri-Nader,merchant_fraud_Barrows PLC,merchant_fraud_Bartoletti and Sons,merchant_fraud_Bartoletti-Wunsch,merchant_fraud_Barton Inc,merchant_fraud_Barton LLC,merchant_fraud_Bashirian Group,merchant_fraud_Bauch-Blanda,merchant_fraud_Bauch-Raynor,merchant_fraud_Baumbach Ltd,"merchant_fraud_Baumbach, Feeney and Morar","merchant_fraud_Baumbach, Hodkiewicz and Walsh","merchant_fraud_Baumbach, Strosin and Nicolas",merchant_fraud_Bechtelar-Rippin,"merchant_fraud_Becker, Harris and Harvey",merchant_fraud_Bednar Group,merchant_fraud_Bednar Inc,merchant_fraud_Bednar PLC,merchant_fraud_Beer-Jast,merchant_fraud_Beier LLC,merchant_fraud_Beier and Sons,merchant_fraud_Beier-Hyatt,merchant_fraud_Berge LLC,"merchant_fraud_Berge, Kautzer and Harris",merchant_fraud_Berge-Hills,merchant_fraud_Berge-Ullrich,merchant_fraud_Bernhard Inc,"merchant_fraud_Bernhard, Grant and Langworth",merchant_fraud_Bernhard-Lesch,merchant_fraud_Bernier and Sons,"merchant_fraud_Bernier, Streich and Jewess","merchant_fraud_Bernier, Volkman and Hoeger","merchant_fraud_Bins, Balistreri and Beatty",merchant_fraud_Bins-Howell,merchant_fraud_Bins-Rice,merchant_fraud_Bins-Tillman,merchant_fraud_Block Group,merchant_fraud_Block-Hauck,merchant_fraud_Block-Parisian,merchant_fraud_Bode-Rempel,merchant_fraud_Bode-Schuster,"merchant_fraud_Boehm, Block and Jakubowski","merchant_fraud_Boehm, Predovic and Reinger",merchant_fraud_Bogisich Inc,merchant_fraud_Bogisich-Homenick,merchant_fraud_Bogisich-Weimann,merchant_fraud_Botsford Ltd,merchant_fraud_Botsford PLC,merchant_fraud_Botsford and Sons,merchant_fraud_Boyer PLC,merchant_fraud_Boyer-Haley,merchant_fraud_Boyer-Reichert,merchant_fraud_Bradtke PLC,"merchant_fraud_Bradtke, Torp and Bahringer",merchant_fraud_Breitenberg LLC,merchant_fraud_Breitenberg-Hermiston,merchant_fraud_Brekke and Sons,merchant_fraud_Brown Inc,merchant_fraud_Brown PLC,"merchant_fraud_Brown, Homenick and Lesch",merchant_fraud_Brown-Greenholt,merchant_fraud_Bruen-Yost,merchant_fraud_Buckridge PLC,merchant_fraud_Carroll PLC,merchant_fraud_Cartwright PLC,merchant_fraud_Cartwright-Harris,"merchant_fraud_Casper, Hand and Zulauf",merchant_fraud_Cassin-Harvey,merchant_fraud_Champlin and Sons,"merchant_fraud_Champlin, Rolfson and Connelly",merchant_fraud_Champlin-Casper,"merchant_fraud_Christiansen, Goyette and Schamberger",merchant_fraud_Christiansen-Gusikowski,merchant_fraud_Cole PLC,"merchant_fraud_Cole, Hills and Jewess",merchant_fraud_Collier Inc,merchant_fraud_Collier LLC,merchant_fraud_Connelly PLC,"merchant_fraud_Connelly, Reichert and Fritsch",merchant_fraud_Connelly-Carter,merchant_fraud_Conroy Ltd,"merchant_fraud_Conroy, Balistreri and Gorczany",merchant_fraud_Conroy-Cruickshank,merchant_fraud_Conroy-Emard,merchant_fraud_Cormier LLC,"merchant_fraud_Cormier, Stracke and Thiel",merchant_fraud_Corwin-Collins,merchant_fraud_Corwin-Gorczany,merchant_fraud_Corwin-Romaguera,"merchant_fraud_Cremin, Hamill and Reichel","merchant_fraud_Crist, Jakubowski and Littel",merchant_fraud_Crona and Sons,"merchant_fraud_Cronin, Kshlerin and Weber",merchant_fraud_Crooks and Sons,merchant_fraud_Cruickshank-Mills,merchant_fraud_Cummerata-Hilpert,merchant_fraud_Cummerata-Jones,merchant_fraud_Cummings Group,merchant_fraud_Cummings LLC,merchant_fraud_Dach-Borer,merchant_fraud_Dach-Nader,"merchant_fraud_Dare, Casper and Bartoletti","merchant_fraud_Dare, Fritsch and Zboncak",merchant_fraud_Dare-Gibson,merchant_fraud_Dare-Marvin,merchant_fraud_Daugherty LLC,"merchant_fraud_Daugherty, Pouros and Beahan",merchant_fraud_Daugherty-Thompson,merchant_fraud_Deckow-Dare,merchant_fraud_Deckow-O'Conner,merchant_fraud_Denesik and Sons,"merchant_fraud_Denesik, Powlowski and Pouros",merchant_fraud_Dibbert and Sons,merchant_fraud_Dibbert-Green,merchant_fraud_Dicki Ltd,merchant_fraud_Dickinson Ltd,merchant_fraud_Dickinson-Rempel,merchant_fraud_Dietrich-Fadel,merchant_fraud_Donnelly LLC,merchant_fraud_Donnelly PLC,merchant_fraud_Dooley Inc,merchant_fraud_Dooley-Thompson,"merchant_fraud_Douglas, DuBuque and McKenzie","merchant_fraud_Douglas, Schneider and Turner",merchant_fraud_Douglas-White,merchant_fraud_Doyle Ltd,merchant_fraud_DuBuque LLC,"merchant_fraud_Durgan, Gislason and Spencer",merchant_fraud_Durgan-Auer,merchant_fraud_Ebert-Daugherty,merchant_fraud_Effertz LLC,"merchant_fraud_Effertz, Welch and Schowalter","merchant_fraud_Eichmann, Bogan and Rodriguez","merchant_fraud_Eichmann, Hayes and Treutel",merchant_fraud_Eichmann-Kilback,merchant_fraud_Eichmann-Russel,merchant_fraud_Emard Inc,merchant_fraud_Emmerich-Luettgen,merchant_fraud_Emmerich-Rau,merchant_fraud_Erdman-Durgan,merchant_fraud_Erdman-Ebert,merchant_fraud_Erdman-Kertzmann,merchant_fraud_Erdman-Schaden,merchant_fraud_Ernser-Feest,merchant_fraud_Ernser-Lynch,merchant_fraud_Fadel Inc,"merchant_fraud_Fadel, Mertz and Rippin",merchant_fraud_Fadel-Hilpert,merchant_fraud_Fahey Inc,"merchant_fraud_Feil, Hilpert and Koss",merchant_fraud_Feil-Morar,"merchant_fraud_Ferry, Lynch and Kautzer","merchant_fraud_Ferry, Reichel and DuBuque",merchant_fraud_Fisher Inc,merchant_fraud_Fisher-Schowalter,merchant_fraud_Flatley Group,merchant_fraud_Flatley-Durgan,merchant_fraud_Frami Group,merchant_fraud_Friesen Inc,merchant_fraud_Friesen Ltd,merchant_fraud_Friesen-D'Amore,merchant_fraud_Friesen-Ortiz,merchant_fraud_Friesen-Stamm,merchant_fraud_Fritsch LLC,merchant_fraud_Fritsch and Sons,merchant_fraud_Funk Group,merchant_fraud_Gaylord-Powlowski,merchant_fraud_Gerhold LLC,merchant_fraud_Gerlach Inc,merchant_fraud_Gibson-Deckow,merchant_fraud_Gislason Group,merchant_fraud_Gleason and Sons,merchant_fraud_Gleason-Macejkovic,"merchant_fraud_Goldner, Kovacek and Abbott",merchant_fraud_Goldner-Lemke,merchant_fraud_Goodwin-Nitzsche,merchant_fraud_Gottlieb Group,"merchant_fraud_Gottlieb, Considine and Schultz",merchant_fraud_Gottlieb-Hansen,merchant_fraud_Goyette Inc,"merchant_fraud_Goyette, Howell and Collier",merchant_fraud_Goyette-Gerhold,merchant_fraud_Goyette-Herzog,merchant_fraud_Graham and Sons,"merchant_fraud_Graham, Hegmann and Hammes","merchant_fraud_Greenfelder, Bartoletti and Davis",merchant_fraud_Greenholt Ltd,"merchant_fraud_Greenholt, Jacobi and Gleason","merchant_fraud_Greenholt, O'Hara and Balistreri",merchant_fraud_Grimes LLC,merchant_fraud_Gulgowski LLC,merchant_fraud_Gutmann Ltd,"merchant_fraud_Gutmann, McLaughlin and Wiza",merchant_fraud_Gutmann-Upton,merchant_fraud_Haag-Blanda,merchant_fraud_Hackett Group,merchant_fraud_Hackett-Lueilwitz,"merchant_fraud_Hagenes, Hermann and Stroman","merchant_fraud_Hagenes, Kohler and Hoppe","merchant_fraud_Hahn, Bahringer and McLaughlin","merchant_fraud_Hahn, Douglas and Schowalter",merchant_fraud_Haley Group,"merchant_fraud_Haley, Batz and Auer","merchant_fraud_Haley, Jewess and Bechtelar",merchant_fraud_Halvorson Group,merchant_fraud_Hamill-D'Amore,merchant_fraud_Hamill-Daugherty,merchant_fraud_Hammes-Beatty,merchant_fraud_Harber Inc,merchant_fraud_Harris Group,merchant_fraud_Harris Inc,"merchant_fraud_Harris, Gusikowski and Heaney","merchant_fraud_Hartmann, Rowe and Hermann","merchant_fraud_Hauck, Dietrich and Funk","merchant_fraud_Hayes, Marquardt and Dibbert",merchant_fraud_Heaney-Marquardt,merchant_fraud_Heathcote LLC,"merchant_fraud_Heathcote, Yost and Kertzmann",merchant_fraud_Heidenreich PLC,merchant_fraud_Heller PLC,"merchant_fraud_Heller, Gutmann and Zieme",merchant_fraud_Heller-Abshire,merchant_fraud_Heller-Langosh,merchant_fraud_Herman Inc,"merchant_fraud_Herman, Treutel and Dickens",merchant_fraud_Hermann and Sons,merchant_fraud_Hermann-Gaylord,"merchant_fraud_Hermiston, Pacocha and Smith","merchant_fraud_Hermiston, Russel and Price",merchant_fraud_Herzog Ltd,"merchant_fraud_Hettinger, McCullough and Fay",merchant_fraud_Hickle Group,"merchant_fraud_Hills, Hegmann and Schaefer",merchant_fraud_Hills-Boyer,merchant_fraud_Hills-Olson,merchant_fraud_Hills-Witting,merchant_fraud_Hilpert-Conroy,"merchant_fraud_Hintz, Bauch and Smith",merchant_fraud_Hintz-Bruen,merchant_fraud_Hirthe-Beier,"merchant_fraud_Hodkiewicz, Prohaska and Paucek",merchant_fraud_Homenick LLC,"merchant_fraud_Hoppe, Harris and Bednar",merchant_fraud_Hoppe-Parisian,merchant_fraud_Howe Ltd,merchant_fraud_Howe PLC,merchant_fraud_Hudson-Grady,merchant_fraud_Hudson-Ratke,merchant_fraud_Huel Ltd,"merchant_fraud_Huel, Hammes and Witting",merchant_fraud_Huel-Langworth,merchant_fraud_Huels-Hahn,merchant_fraud_Huels-Nolan,"merchant_fraud_Hyatt, Russel and Gleichner",merchant_fraud_Hyatt-Blick,merchant_fraud_Jacobi Inc,merchant_fraud_Jacobi and Sons,merchant_fraud_Jakubowski Group,merchant_fraud_Jakubowski Inc,merchant_fraud_Jaskolski-Dibbert,merchant_fraud_Jaskolski-Vandervort,merchant_fraud_Jast Ltd,merchant_fraud_Jast and Sons,merchant_fraud_Jast-McDermott,"merchant_fraud_Jenkins, Hauck and Friesen",merchant_fraud_Jerde-Hermann,merchant_fraud_Jewess LLC,merchant_fraud_Johns Inc,merchant_fraud_Johns-Hoeger,"merchant_fraud_Johnson, Runolfsdottir and Mayer","merchant_fraud_Johnston, Nikolaus and Maggio",merchant_fraud_Johnston-Casper,"merchant_fraud_Jones, Sawayn and Romaguera",merchant_fraud_Kassulke Inc,merchant_fraud_Kassulke PLC,merchant_fraud_Kautzer and Sons,merchant_fraud_Keeling-Crist,merchant_fraud_Kemmer-Buckridge,merchant_fraud_Kemmer-Reinger,merchant_fraud_Kerluke Inc,merchant_fraud_Kerluke PLC,"merchant_fraud_Kerluke, Considine and Macejkovic","merchant_fraud_Kerluke, Kertzmann and Wiza",merchant_fraud_Kerluke-Abshire,merchant_fraud_Kertzmann LLC,merchant_fraud_Kessler Group,merchant_fraud_Kessler Inc,merchant_fraud_Kiehn Inc,merchant_fraud_Kiehn-Emmerich,merchant_fraud_Kihn Inc,"merchant_fraud_Kihn, Abernathy and Douglas","merchant_fraud_Kihn, Brakus and Goyette",merchant_fraud_Kihn-Fritsch,merchant_fraud_Kihn-Schuster,merchant_fraud_Kilback Group,merchant_fraud_Kilback LLC,merchant_fraud_Kilback and Sons,"merchant_fraud_Kilback, Nitzsche and Leffler",merchant_fraud_Kirlin and Sons,merchant_fraud_Klein Group,merchant_fraud_Kling Inc,"merchant_fraud_Kling, Howe and Schneider",merchant_fraud_Kling-Ernser,merchant_fraud_Kling-Grant,merchant_fraud_Klocko LLC,"merchant_fraud_Klocko, Runolfsdottir and Breitenberg",merchant_fraud_Koelpin and Sons,merchant_fraud_Koepp-Parker,merchant_fraud_Koepp-Witting,"merchant_fraud_Kohler, Lindgren and Koelpin","merchant_fraud_Konopelski, Schneider and Hartmann",merchant_fraud_Koss and Sons,"merchant_fraud_Koss, Hansen and Lueilwitz","merchant_fraud_Koss, McLaughlin and Mayer",merchant_fraud_Kovacek Ltd,"merchant_fraud_Kovacek, Dibbert and Ondricka",merchant_fraud_Kozey-Boehm,merchant_fraud_Kozey-Kuhlman,merchant_fraud_Kozey-McDermott,merchant_fraud_Kris-Kertzmann,merchant_fraud_Kris-Padberg,merchant_fraud_Kris-Weimann,merchant_fraud_Kub PLC,merchant_fraud_Kub-Heaney,merchant_fraud_Kuhic Inc,merchant_fraud_Kuhic LLC,"merchant_fraud_Kuhic, Bins and Pfeffer",merchant_fraud_Kuhn Group,merchant_fraud_Kuhn LLC,merchant_fraud_Kulas Group,merchant_fraud_Kunde-Sanford,merchant_fraud_Kunze Inc,"merchant_fraud_Kunze, Larkin and Mayert",merchant_fraud_Kuphal-Bartoletti,merchant_fraud_Kuphal-Predovic,merchant_fraud_Kuphal-Toy,merchant_fraud_Kutch Group,merchant_fraud_Kutch LLC,merchant_fraud_Kutch and Sons,"merchant_fraud_Kutch, Hermiston and Farrell","merchant_fraud_Kutch, Steuber and Gerhold",merchant_fraud_Kutch-Ferry,merchant_fraud_Kutch-Hegmann,merchant_fraud_Kutch-Wilderman,merchant_fraud_Kuvalis Ltd,merchant_fraud_Labadie LLC,"merchant_fraud_Labadie, Treutel and Bode","merchant_fraud_Lakin, Ferry and Beatty","merchant_fraud_Lang, Towne and Schuppe","merchant_fraud_Langosh, Wintheiser and Hyatt",merchant_fraud_Langworth LLC,"merchant_fraud_Langworth, Boehm and Gulgowski",merchant_fraud_Larkin Ltd,"merchant_fraud_Larkin, Stracke and Greenfelder","merchant_fraud_Larson, Quitzon and Spencer",merchant_fraud_Larson-Moen,merchant_fraud_Leannon-Nikolaus,merchant_fraud_Leannon-Ward,merchant_fraud_Lebsack and Sons,"merchant_fraud_Ledner, Hartmann and Feest",merchant_fraud_Ledner-Pfannerstill,merchant_fraud_Leffler-Goldner,"merchant_fraud_Lehner, Mosciski and King","merchant_fraud_Lehner, Reichert and Mills",merchant_fraud_Lemke and Sons,merchant_fraud_Lemke-Gutmann,merchant_fraud_Lesch Ltd,"merchant_fraud_Lesch, D'Amore and Brown","merchant_fraud_Lind, Huel and McClure",merchant_fraud_Lind-Buckridge,merchant_fraud_Little Ltd,"merchant_fraud_Little, Gutmann and Lynch",merchant_fraud_Little-Gleichner,merchant_fraud_Lockman Ltd,"merchant_fraud_Lockman, West and Runte","merchant_fraud_Lowe, Dietrich and Erdman","merchant_fraud_Lubowitz, Terry and Stracke",merchant_fraud_Lubowitz-Walter,merchant_fraud_Luettgen PLC,merchant_fraud_Lynch Ltd,merchant_fraud_Lynch-Mohr,merchant_fraud_Lynch-Wisozk,merchant_fraud_Macejkovic-Lesch,merchant_fraud_Maggio-Fahey,merchant_fraud_Mante Group,"merchant_fraud_Mante, Luettgen and Hackett",merchant_fraud_Marks Inc,merchant_fraud_Marvin-Lind,merchant_fraud_Mayert Group,merchant_fraud_McCullough Group,merchant_fraud_McCullough LLC,"merchant_fraud_McCullough, Hudson and Schuster","merchant_fraud_McDermott, Osinski and Morar",merchant_fraud_McDermott-Rice,merchant_fraud_McDermott-Weimann,merchant_fraud_McGlynn-Heathcote,merchant_fraud_McGlynn-Jaskolski,merchant_fraud_McKenzie-Huels,"merchant_fraud_McLaughlin, Armstrong and Koepp",merchant_fraud_Medhurst Inc,merchant_fraud_Medhurst PLC,"merchant_fraud_Medhurst, Cartwright and Ebert","merchant_fraud_Medhurst, Labadie and Gottlieb","merchant_fraud_Metz, Russel and Metz",merchant_fraud_Metz-Boehm,merchant_fraud_Miller-Harris,merchant_fraud_Miller-Hauck,"merchant_fraud_Moen, Reinger and Murphy",merchant_fraud_Mohr Inc,merchant_fraud_Mohr-Bayer,"merchant_fraud_Monahan, Bogisich and Ledner","merchant_fraud_Monahan, Hermann and Johns",merchant_fraud_Monahan-Morar,"merchant_fraud_Moore, Dibbert and Koepp","merchant_fraud_Moore, Williamson and Emmerich",merchant_fraud_Morar Inc,merchant_fraud_Morissette LLC,merchant_fraud_Morissette PLC,"merchant_fraud_Morissette, Weber and Wiegand",merchant_fraud_Morissette-Schaefer,merchant_fraud_Mosciski Group,"merchant_fraud_Mosciski, Gislason and Mertz","merchant_fraud_Mosciski, Ziemann and Farrell",merchant_fraud_Mraz-Herzog,"merchant_fraud_Mueller, Gerhold and Mueller",merchant_fraud_Murray Ltd,merchant_fraud_Murray-Smitham,merchant_fraud_Nader-Heller,merchant_fraud_Nader-Maggio,"merchant_fraud_Nicolas, Hills and McGlynn",merchant_fraud_Nienow PLC,"merchant_fraud_Nienow, Ankunding and Collier","merchant_fraud_Nienow, Barrows and Romaguera","merchant_fraud_Nitzsche, Kessler and Wolff",merchant_fraud_Nolan-Williamson,"merchant_fraud_O'Connell, Botsford and Hand",merchant_fraud_O'Connell-Ullrich,merchant_fraud_O'Hara-Wilderman,merchant_fraud_O'Keefe-Hudson,merchant_fraud_O'Keefe-Wisoky,"merchant_fraud_O'Reilly, Mohr and Purdy","merchant_fraud_Okuneva, Schneider and Rau","merchant_fraud_Olson, Becker and Koch",merchant_fraud_Ortiz Group,merchant_fraud_Osinski Inc,"merchant_fraud_Osinski, Ledner and Leuschke",merchant_fraud_Pacocha-Bauch,merchant_fraud_Pacocha-O'Reilly,merchant_fraud_Pacocha-Weissnat,merchant_fraud_Padberg-Rogahn,merchant_fraud_Padberg-Sauer,merchant_fraud_Padberg-Welch,merchant_fraud_Pagac LLC,merchant_fraud_Parisian and Sons,"merchant_fraud_Parisian, Schiller and Altenwerth","merchant_fraud_Parker, Nolan and Trantow",merchant_fraud_Parker-Kunde,merchant_fraud_Paucek-Wiza,merchant_fraud_Pfeffer LLC,merchant_fraud_Pfeffer and Sons,merchant_fraud_Pollich LLC,"merchant_fraud_Pouros, Walker and Spencer",merchant_fraud_Pouros-Conroy,merchant_fraud_Pouros-Haag,merchant_fraud_Powlowski-Weimann,merchant_fraud_Predovic Inc,merchant_fraud_Price Inc,merchant_fraud_Prohaska-Murray,merchant_fraud_Prosacco LLC,"merchant_fraud_Prosacco, Kreiger and Kovacek","merchant_fraud_Quitzon, Green and Bashirian",merchant_fraud_Quitzon-Goyette,merchant_fraud_Ratke and Sons,merchant_fraud_Rau and Sons,merchant_fraud_Rau-Grant,merchant_fraud_Rau-Robel,"merchant_fraud_Raynor, Feest and Miller","merchant_fraud_Raynor, Reinger and Hagenes",merchant_fraud_Reichel Inc,merchant_fraud_Reichel LLC,"merchant_fraud_Reichel, Bradtke and Blanda","merchant_fraud_Reichert, Huels and Hoppe","merchant_fraud_Reichert, Rowe and Mraz","merchant_fraud_Reichert, Shanahan and Hayes",merchant_fraud_Reichert-Weissnat,merchant_fraud_Reilly LLC,merchant_fraud_Reilly and Sons,"merchant_fraud_Reilly, Heaney and Cole","merchant_fraud_Reinger, Weissnat and Strosin",merchant_fraud_Rempel Inc,merchant_fraud_Rempel PLC,merchant_fraud_Renner Ltd,merchant_fraud_Reynolds-Schinner,"merchant_fraud_Rippin, Kub and Mann",merchant_fraud_Rippin-VonRueden,"merchant_fraud_Ritchie, Bradtke and Stiedemann","merchant_fraud_Ritchie, Oberbrunner and Cremin","merchant_fraud_Robel, Cummerata and Prosacco","merchant_fraud_Roberts, Daniel and Macejkovic","merchant_fraud_Roberts, Ryan and Smith",merchant_fraud_Roberts-Beahan,merchant_fraud_Rodriguez Group,"merchant_fraud_Rodriguez, Yost and Jenkins","merchant_fraud_Rohan, White and Aufderhar",merchant_fraud_Rolfson-Kunde,merchant_fraud_Romaguera Ltd,merchant_fraud_Romaguera and Sons,"merchant_fraud_Romaguera, Cruickshank and Greenholt","merchant_fraud_Romaguera, Wehner and Tromp",merchant_fraud_Roob LLC,"merchant_fraud_Roob, Conn and Tremblay",merchant_fraud_Roob-Okuneva,"merchant_fraud_Rowe, Batz and Goodwin",merchant_fraud_Rowe-Vandervort,merchant_fraud_Ruecker Group,"merchant_fraud_Ruecker, Beer and Collier",merchant_fraud_Ruecker-Mayert,"merchant_fraud_Runolfsdottir, Mueller and Hand",merchant_fraud_Runolfsson and Sons,"merchant_fraud_Runte, Green and Emard",merchant_fraud_Runte-Mohr,"merchant_fraud_Rutherford, Homenick and Bergstrom",merchant_fraud_Rutherford-Mertz,merchant_fraud_Satterfield-Lowe,merchant_fraud_Sawayn PLC,merchant_fraud_Schaefer Ltd,"merchant_fraud_Schaefer, Fay and Hilll","merchant_fraud_Schaefer, Maggio and Daugherty","merchant_fraud_Schaefer, McGlynn and Bosco",merchant_fraud_Schamberger-O'Keefe,merchant_fraud_Schiller Ltd,"merchant_fraud_Schiller, Blanda and Johnson",merchant_fraud_Schimmel-Olson,merchant_fraud_Schmeler Inc,"merchant_fraud_Schmeler, Bashirian and Price",merchant_fraud_Schmeler-Howe,merchant_fraud_Schmidt and Sons,merchant_fraud_Schmidt-Larkin,merchant_fraud_Schmitt Inc,merchant_fraud_Schmitt Ltd,"merchant_fraud_Schneider, Hayes and Nikolaus",merchant_fraud_Schoen Ltd,"merchant_fraud_Schoen, Kuphal and Nitzsche","merchant_fraud_Schoen, Nienow and Bauch",merchant_fraud_Schoen-Quigley,merchant_fraud_Schroeder Group,"merchant_fraud_Schroeder, Hauck and Treutel","merchant_fraud_Schroeder, Wolff and Hermiston",merchant_fraud_Schulist Ltd,"merchant_fraud_Schultz, Simonis and Little",merchant_fraud_Schumm PLC,"merchant_fraud_Schumm, Bauch and Ondricka","merchant_fraud_Schumm, McLaughlin and Carter",merchant_fraud_Schuppe LLC,"merchant_fraud_Schuppe, Nolan and Hoeger",merchant_fraud_Schuppe-Schuppe,merchant_fraud_Shanahan-Lehner,merchant_fraud_Shields Inc,merchant_fraud_Shields-Wunsch,merchant_fraud_Simonis-Prohaska,merchant_fraud_Skiles LLC,merchant_fraud_Skiles-Ankunding,merchant_fraud_Smith-Stokes,merchant_fraud_Smitham-Boehm,merchant_fraud_Smitham-Schiller,merchant_fraud_Spencer PLC,merchant_fraud_Spencer-R